### ISSUE TITLE
Question regarding logging

### ISSUE THREAD

**Issue by Chaprnks** [maddinat0r/samp-discord-connector#78]
I've noticed that the log definitions are now in the include, does this mean that we can change discord logging? (warn, error, none etc)

![lpz2kqo](https://user-images.githubusercontent.com/6340970/43996639-09492890-9d95-11e8-86f6-79ab32201d46.png)

**Comment by Chaprnks** [comment]
Is this still the case? Curious how the project is coming along :)

**Comment by maddinat0r** [comment]
The logging system is still in the works. You can check the progress of it here: https://github.com/maddinat0r/samp-log-core

**Comment by maddinat0r** [comment]
The next log-core update is now mostly finished. Setting the log level will now happen through a central config file, looking like this for example:
```yaml
Logger:
  plugins/discord-connector:
    LogLevel: All
    LogRotation:
      Type: Size
      Trigger: 20MB
      BackupCount: 5
    Append: false
    PrintToConsole: false
LogLevel:
  Error:
    PrintToConsole: true
EnableColors: true
LogTimeFormat: '%F %H:%M:%S'
```
